"""
OpsSwarm — SQLAlchemy Database Models
=======================================
Defines all PostgreSQL tables using SQLAlchemy 2.0 async ORM.

Tables:
  - incidents          → Core incident records
  - rca_reports        → Root cause analysis outputs
  - agent_decisions    → Every decision made by every agent
  - audit_logs         → Immutable audit trail for compliance
  - remediations       → Record of all remediation actions taken

Usage:
    from core.database_models import Incident, RCAReport, Base
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


# ─── BASE ─────────────────────────────────────────────────────────────────────

class Base(DeclarativeBase):
    """Base class for all ORM models."""
    pass


class TimestampMixin:
    """Adds created_at and updated_at to any model."""
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


# ─── INCIDENTS ────────────────────────────────────────────────────────────────

class Incident(TimestampMixin, Base):
    """
    Core incident record. Created when Sentry detects an anomaly.
    Updated throughout the pipeline as agents process it.
    """
    __tablename__ = "incidents"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: f"INC-{uuid.uuid4().hex[:8].upper()}",
        comment="Human-readable incident ID, e.g. INC-A1B2C3D4",
    )
    correlation_id: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        nullable=False,
        index=True,
        comment="UUID linking this incident to its pipeline run",
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Classification
    severity: Mapped[str] = mapped_column(
        String(16), nullable=False, index=True,
        comment="INFO | LOW | MEDIUM | HIGH | CRITICAL",
    )
    event_type: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    error_code: Mapped[str | None] = mapped_column(String(32), nullable=True)
    affected_service: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    affected_host: Mapped[str | None] = mapped_column(String(128), nullable=True)
    affected_region: Mapped[str] = mapped_column(String(32), default="us-east-1")

    # Lifecycle
    status: Mapped[str] = mapped_column(
        String(32), nullable=False,
        default="DETECTED", index=True,
        comment="IncidentStatus enum value",
    )
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Risk
    risk_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_level: Mapped[str | None] = mapped_column(String(16), nullable=True)
    sla_breach_risk: Mapped[bool] = mapped_column(Boolean, default=False)

    # Alert data
    alert_count: Mapped[int] = mapped_column(Integer, default=1)
    raw_alert_ids: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)

    # Business context
    service_owner: Mapped[str | None] = mapped_column(String(128), nullable=True)
    business_impact: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Relationships
    rca_reports: Mapped[list["RCAReport"]] = relationship(
        "RCAReport", back_populates="incident", cascade="all, delete-orphan"
    )
    agent_decisions: Mapped[list["AgentDecision"]] = relationship(
        "AgentDecision", back_populates="incident", cascade="all, delete-orphan"
    )
    remediations: Mapped[list["Remediation"]] = relationship(
        "Remediation", back_populates="incident", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Incident id={self.id!r} severity={self.severity!r} status={self.status!r}>"


# ─── RCA REPORTS ──────────────────────────────────────────────────────────────

class RCAReport(TimestampMixin, Base):
    """
    Root Cause Analysis report. Generated by the Investigator agent.
    Stored here for audit, dashboarding, and future RAG indexing.
    """
    __tablename__ = "rca_reports"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    incident_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )

    # RCA content
    root_cause: Mapped[str] = mapped_column(Text, nullable=False)
    root_cause_summary: Mapped[str] = mapped_column(String(512), nullable=False)
    contributing_factors: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Evidence
    evidence: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    similar_incidents: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)

    # Recommendations
    recommendations: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)

    # Generation metadata
    generated_by: Mapped[str] = mapped_column(String(64), default="investigator")
    model_used: Mapped[str | None] = mapped_column(String(128), nullable=True)
    generation_duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Relationship
    incident: Mapped["Incident"] = relationship("Incident", back_populates="rca_reports")

    def __repr__(self) -> str:
        return f"<RCAReport id={self.id!r} incident={self.incident_id!r} confidence={self.confidence}>"


# ─── AGENT DECISIONS ──────────────────────────────────────────────────────────

class AgentDecision(TimestampMixin, Base):
    """
    Immutable record of every decision made by every agent.
    Critical for auditability, postmortems, and compliance.
    """
    __tablename__ = "agent_decisions"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    incident_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    correlation_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # Decision details
    agent_name: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    action: Mapped[str] = mapped_column(String(255), nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    risk_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    status: Mapped[str] = mapped_column(String(32), default="COMPLETED")
    duration_ms: Mapped[int] = mapped_column(Integer, default=0)

    # Extra context
    metadata_: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata", JSON, nullable=True
    )

    # Relationship
    incident: Mapped["Incident"] = relationship(
        "Incident", back_populates="agent_decisions"
    )

    def __repr__(self) -> str:
        return (
            f"<AgentDecision agent={self.agent_name!r} "
            f"action={self.action!r} incident={self.incident_id!r}>"
        )


# ─── AUDIT LOGS ───────────────────────────────────────────────────────────────

class AuditLog(TimestampMixin, Base):
    """
    Append-only audit trail for compliance and postmortems.
    Never UPDATE or DELETE rows in this table.
    """
    __tablename__ = "audit_logs"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    correlation_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    incident_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)

    # Who / what / when
    actor: Mapped[str] = mapped_column(
        String(128), nullable=False,
        comment="Agent name, user email, or 'system'",
    )
    action: Mapped[str] = mapped_column(String(255), nullable=False)
    resource_type: Mapped[str] = mapped_column(String(64), nullable=False)
    resource_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    # State change
    before_state: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    after_state: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    # Context
    ip_address: Mapped[str | None] = mapped_column(String(45), nullable=True)
    user_agent: Mapped[str | None] = mapped_column(String(255), nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<AuditLog actor={self.actor!r} action={self.action!r}>"


# ─── REMEDIATIONS ─────────────────────────────────────────────────────────────

class Remediation(TimestampMixin, Base):
    """
    Record of every remediation action attempted for an incident.
    Includes approval tracking and rollback information.
    """
    __tablename__ = "remediations"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    incident_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    correlation_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # Action
    action: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    risk_level: Mapped[str] = mapped_column(String(16), nullable=False)
    risk_score: Mapped[float] = mapped_column(Float, nullable=False)

    # Approval
    required_approval: Mapped[bool] = mapped_column(Boolean, default=False)
    approved_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    approval_timestamp: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Execution
    executed: Mapped[bool] = mapped_column(Boolean, default=False)
    executed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    result: Mapped[str | None] = mapped_column(Text, nullable=True)
    success: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    # Rollback
    rollback_action: Mapped[str | None] = mapped_column(String(128), nullable=True)
    rolled_back: Mapped[bool] = mapped_column(Boolean, default=False)
    rolled_back_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationship
    incident: Mapped["Incident"] = relationship(
        "Incident", back_populates="remediations"
    )

    def __repr__(self) -> str:
        return (
            f"<Remediation action={self.action!r} "
            f"executed={self.executed} success={self.success}>"
        )
